### ISSUE TITLE
Progress for MMU on RAMPS/KLIPPER

### ISSUE THREAD

**Issue by troisplus** [trevjonez/klipper-configs#3]
Hi Trevjonez, 
Where are you with your progress with the MMU?
Do you have any BOM and description of your MMUR?

I would be very interested to install it on my A8 running klipper on ramps too.

**Comment by trevjonez** [comment]
so a year later i've still not been able to dedicate the time to get it to where I am comfortable sharing things with the community. I believe there is some other community members that have it working at a proof of concept level. but the last I saw in discord was that it was not yet very robust?

One way to stay up to date with my work on it is to check in on my fork of klipper though the last I looked into it was in may and ended up spending most of my time just catching up with the upstream klipper changes. Additionally it is important to keep in mind that my work is also trying to support the mmu2 board designed by prusa as well as the kinematics of the mmu2 assembly. this. will allow you to build the prusa kit with or without their mcu control board

going to close this for now since it has regrettably been missed and gone stale for so long.

here is maybe a lead on when the community has to offer. https://github.com/kakou-fr/mmu2_1S_klipper_config
